### ISSUE TITLE
Port to fabric 1.19 +

### ISSUE THREAD

**Issue by TecEash1** [XFactHD/LogitechGLights#2]
Hi, is there any way that this can be ported to fabric 1.19 + - if you can I would appreciate it greatly - I don't know if this mod is still active but if u can/ are able to that would be great.

**Comment by XFactHD** [comment]
This mod is dead. It was a small experiment that didn't really work out as planned.
I also currently have no interest in porting any of my mods to Fabric, so, if anything, I would continue it on Forge.
